### ISSUE TITLE
Space Fucker board

### ISSUE THREAD

**Issue by spacefucker** [ARRRmada/ARRRmada.com#9]
### Submission Type

New listing

### Merchant Listing Code

---BEGIN CODE---
JTVCJTIyUGtNTlVlbkQlMjIlMkMlMjJTcGFjZSUyMEZ1Y2tlciUyMiUyQyUyMlNleCUyMGRpc2N1c3Npb24lMjBib2FyZC4lMjBBY2NlcHQlMjBBUlJSJTIwZm9yJTIwYWNjb3VudCUyMHVwZ3JhZGVzJTIwcGF5bWVudHMuJTIyJTJDJTIyMjAyMy0xMC0xOS0xMjU4MjcucG5nJTIyJTJDJTIyaHR0cHMlM0ElMkYlMkZ3d3cuc3BhY2VmdWNrZXIuY29tJTJGJTIyJTJDJTVCJTIyMzElMjIlNUQlNUQ=
---END CODE---

### Merchant Listing Image

![2023-10-19-125827](https://github.com/ARRRmada/ARRRmada.com/assets/38446100/4dec5a27-449f-4be6-964b-5d5f17602268)

### Comments for listing reviewer (optional)

accepting ARRR for account upgrades and all other paid features.

**Comment by spacefucker** [comment]
https://www.spacefucker.com/threads/spacefucker-paid-features.363314/

**Comment by scott-ftf** [comment]
Hello @spacefucker 

Thanks for taking the time to generate a listing for ARRRmada, and its great to see you are accepting ARRR for payments. After reviewing the listing, because the website promotes incest and family sex, we can not approve this listing at this time as it does not meet the listing guidelines. We have to protect the domain from being blacklisted. Thanks for your understanding.

**Comment by spacefucker** [comment]
Okay. if you will create adult list on other domain, add it into it please
